# download_config.yaml
action: download
output-filename: null           # do not touch
data-file: null                 # do not touch
coords-dir: geojsons            # directory of JSON files | nothing
start: 2022-08-01T00:00:00      # format: YYYY-MM-DDTHH:MM:SS
end: 2022-08-02T23:00:00        # format: YYYY-MM-DDTHH:MM:SS
preds: [TA, PA, P, WS, WD, USTAR, NETRAD, SW_IN, SW_IN_POT, SW_OUT, LW_IN, LW_OUT, LE, G, H, VPD, RH, CO2]        # AmeriFlux predictors | nothing
aggregation-type:        # DAILY | MONTHLY | nothing
timezone-aware: YES               # YES | NO
id-field: GID                       # Identifier field | nothing