# download_config.yaml
action: download
output-filename: null           # do not touch
data-file: null                 # do not touch
coords-dir: geojsons           # directory of JSON files | nothing
start: 2015-01-01T00:00:00      # format: YYYY-MM-DDTHH:MM:SS
end: 2015-01-01T23:00:00        # format: YYYY-MM-DDTHH:MM:SS
preds: [TA, RH, WS, WD]         # AmeriFlux predictors | nothing
aggregation-type:  DAILY         # DAILY | MONTHLY | nothing
