# process_config.yaml
action: process
output-filename: test   # suffix of the output files
data-file:              # CSV file or nothing (for gap-filling on specific EC tower site)
coords-file: null       # do not touch
start: null             # do not touch
end: null               # do not touch
preds: []               # do not touch