# process_config.yaml
action: process
output-filename: test   # suffix of the output files
data-file:              # CSV | nothing (for gap-filling on specific EC tower site)
coords-dir: null        # do not touch
start: null             # do not touch
end: null               # do not touch
preds: []               # do not touch
aggregation-type: null  # do not touch
id-field:               # do not touch